### PR TITLE
Added explanation to index.ipynb

### PR DESCRIPTION
**Pull request by pablobernabeu**
Added explanation to index.ipynb: 'File serving the purpose of creating a Binder repo (https://github.com/binder-examples/r).'

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey @pablobernabeu - thanks for opening the PR. Could you explain the confusion that you're trying to clear up with this PR? Thanks

**Comment by pablobernabeu** [comment]
Hi @choldgraf - Of course. The note explains the reason why the 'index.ipynb' file must be present in the repository. In other words, if this file is removed, the repo can no longer be deployed to Binder (at least the RStudio and the Shiny environments cannot, as far as I experienced).

**Comment by choldgraf** [comment]
Hmmm - that actually feels like a bug though, instead of expected behavior. The `index.ipynb` file shouldn't be needed to run a shiny dashboard. What was the behavior you experienced when removing index.ipynb?

**Comment by pablobernabeu** [comment]
Hi @choldgraf, 

I've just double-checked this and both RStudio and Shiny can be deployed even without having the index.ipynb file. Great to know! Thanks, and sorry for the confusion. 

All the best

**Comment by choldgraf** [comment]
wohoo - glad it worked :-)

**Pull request closed without merging**
